# \u76D1\u542C\u7AEF\u53E3\u4E3A 8000\uFF08\u9ED8\u8BA4\u4E3A 8080\uFF09
server.port=8000

# \u5E94\u7528\u540D\u79F0
spring.application.name=springboot-starter

# \u542F\u7528\u81EA\u52A8\u91CD\u542F (\u9ED8\u8BA4\u5C31\u662F true)
spring.devtools.restart.enabled=true

# \u6570\u636E\u5E93\u914D\u7F6E (DataSource)
spring.datasource.url=jdbc:mysql://localhost:3306/springboot_db?characterEncoding=utf-8
spring.datasource.username=root
spring.datasource.password=123456
